basePath: /
definitions:
  user.LoginResponse:
    properties:
      token:
        example: eyJhbGciOijiwzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJpc3N1ZXIiLCJhsIiOiJzdWJqZWN0IiwiYXVkIjpbImF1ZGllbmNlIl0sImV4cCI6MTc0NTQ2NzM0MywibmJmIjoxNzQ1NhtbMjgzLCJpYXQiOjE3NDU0NjcyODMsImp0aSI6ImlkIn0.dxgM6uH2F8ZglV_xcPhjCRnOSJBYq9oeS1TDLkLg_eg
        type: string
    type: object
host: localhost:5000
info:
  contact: {}
  description: Feedo API documentation
  title: Feedo API
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: This is a user login endpoint
      parameters:
      - description: Username
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Returns JWT token
          schema:
            $ref: '#/definitions/user.LoginResponse'
      summary: User login endpoint
      tags:
      - user
swagger: "2.0"
